version: '3.5'

services:
  nginx:
    container_name: secret_stuffs_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - server

  server:
    container_name: secret_stuffs_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/secret-stuff-backend:${TAG:-latest}
    depends_on:
      - db
    ports:
      - '0.0.0.0:8082:8082'
    expose:
      - '8082'

  db:
    container_name: secret_stuffs_db
    image: postgres:15.3
    command: ['postgres', '-c', 'log_statement=all']
    expose:
      - '5432'
    ports:
      - '0.0.0.0:5432:5432'
    environment:
      - POSTGRES_DB=secret_stuffs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    container_name: secret_stuffs_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/secret-stuff-frontend:${TAG:-latest}
    ports:
      - "3000"
    environment:
      - VITE_API_BASE_URL=/api
      - VITE_WEBSOCKET_BASE_URL=/ws
    depends_on:
      - server

volumes:
  db-data:

networks:
  default:
    name: app-network
